# Generated by Django 4.2.7 on 2024-11-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spamwebsite',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='spamwebsite',
            name='website_url',
        ),
        migrations.AlterField(
            model_name='spamwebsite',
            name='spam_type',
            field=models.CharField(max_length=50),
        ),
    ]
